import { Colors } from '../theme.d';

const BODY_BACKGROUND_COLOR = '#ffffff';

const PRIMARY_LOADER_COFFEE_CUP_BORDER = '#000000';
const PRIMARY_LOADER_COFFEE_CUP_BORDER_AFTER = '#000000';
const PRIMARY_LOADER_COFFEE_CUP_BORDER_BEFORE = '#bfbfbf';
const PRIMARY_LOADER_COFFEE_CUP_BEFORE_BOX_SHADOW = '#bfbfbf';

const DEFAULT_THEME_COLORS: Colors = {
  BODY_BACKGROUND_COLOR,
  PRIMARY_LOADER_COFFEE_CUP_BORDER,
  PRIMARY_LOADER_COFFEE_CUP_BORDER_AFTER,
  PRIMARY_LOADER_COFFEE_CUP_BORDER_BEFORE,
  PRIMARY_LOADER_COFFEE_CUP_BEFORE_BOX_SHADOW,
};

export default DEFAULT_THEME_COLORS;
